version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    commit-message:
      prefix: fix(deps)
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: daily
    commit-message:
      prefix: fix(deps)
  - package-ecosystem: docker
    directory: /docker
    schedule:
      interval: daily
    commit-message:
      prefix: fix(deps)
