# https://github.com/DavidAnson/markdownlint/blob/main/schema/.markdownlint.yaml
# https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md

# Default state for all rules
default: true

# MD013/line-length - Line length
MD013:
  line_length: 300
