version: '3.8'
services:
  storage-redis:
    image: redis:6
    container_name: storage-redis
    ports:
      - 6379:6379
    volumes:
      - ./scratch/redisdata:/data
    entrypoint: [ "redis-server", "--appendonly", "yes" ]

  funnel-rocket-worker:
    build:
      dockerfile: docker/Dockerfile
      target: prod
      context: .
    image: dynamicyield/frocket
    environment:
      - FROCKET_REDIS_HOST=storage-redis
    tty: true
    depends_on:
      - storage-redis
    command: worker

  funnel-rocket-api-server:
    image: dynamicyield/frocket
    container_name: frocket-api-server
    ports:
      - 5000:5000
    environment:
      - FROCKET_REDIS_HOST=storage-redis
      - FLASK_APP=frocket/apiserver.py
    tty: true
    depends_on:
      - storage-redis
    command: apiserver
