version: '3.8'
services:
  redis:
    image: redis:6
    container_name: redis
    ports:
      - 6380:6380
    entrypoint: [ "redis-server", "--port", "6380" ]

  mock-s3:
    image: frocket/minio-server-autostart:latest
    container_name: mock-s3
    ports:
      - 9000:9000

  frocket-worker:
    build:
      dockerfile: docker/Dockerfile
      target: prod
      context: .
    image: dynamicyield/frocket
    environment:
      - FROCKET_REDIS_HOST=redis
      - FROCKET_REDIS_PORT=6380
      - FROCKET_AWS_ENDPOINT_URL=http://mock-s3:9000
      - FROCKET_AWS_ACCESS_KEY_ID=testonly
      - FROCKET_AWS_SECRET_ACCESS_KEY=testonly
    tty: true
    depends_on:
      - redis
    command: worker

  frocket-apiserver:
    image: dynamicyield/frocket
    container_name: frocket-apiserver
    ports:
      - 5000:5000
    environment:
      - FROCKET_REDIS_HOST=redis
      - FROCKET_REDIS_PORT=6380
      - FROCKET_AWS_ENDPOINT_URL=http://mock-s3:9000
      - FROCKET_AWS_ACCESS_KEY_ID=testonly
      - FROCKET_AWS_SECRET_ACCESS_KEY=testonly
      - FLASK_APP=frocket/apiserver.py
    tty: true
    depends_on:
      - redis
    command: apiserver
