version: '3.8'
services:
  redis:
    image: redis:6
    ports:
      - ${FROCKET_REDIS_PORT:-6379}:${FROCKET_REDIS_PORT:-6379}
    entrypoint: [ "redis-server", "--port", "${FROCKET_REDIS_PORT:-6379}" ]

  mock-s3:
    image: minio/minio:latest
    container_name: mock-s3
    ports:
      - 9000:9000
    environment:
      - MINIO_ROOT_USER=testonly
      - MINIO_ROOT_PASSWORD=testonly
    command: server /data

  frocket-queue-worker:
    build:
      dockerfile: docker/all-in-one.Dockerfile
      context: .
    image: frocket/all-in-one:latest
    volumes:
      - ./data:/app/data:ro,cached
    environment:
      - FROCKET_REDIS_HOST=redis
      - FROCKET_REDIS_PORT=${FROCKET_REDIS_PORT:-6379}
      - FROCKET_S3_AWS_ENDPOINT_URL=http://mock-s3:9000
      - FROCKET_S3_AWS_ACCESS_KEY_ID=testonly
      - FROCKET_S3_AWS_SECRET_ACCESS_KEY=testonly
    depends_on:
      - redis
      - mock-s3
    command: worker

  frocket-lambda-worker:
    build:
      dockerfile: docker/local-lambda.Dockerfile
      context: .
    image: frocket/local-lambda:latest
    container_name: mock-lambda
    volumes:
      - ./data:/var/task/data:ro,cached
    environment:
      - FROCKET_REDIS_HOST=redis
      - FROCKET_REDIS_PORT=${FROCKET_REDIS_PORT:-6379}
      - FROCKET_S3_AWS_ENDPOINT_URL=http://mock-s3:9000
      - FROCKET_S3_AWS_ACCESS_KEY_ID=testonly
      - FROCKET_S3_AWS_SECRET_ACCESS_KEY=testonly
      - AWS_REGION=us-east-1
    depends_on:
      - redis
      - mock-s3
    ports:
      - 9001:9001
    command: frocket.worker.impl.aws_lambda_worker.lambda_handler

  frocket-apiserver:
    image: frocket/all-in-one:latest
    container_name: frocket-apiserver
    ports:
      - 5000:5000
    volumes:
      - ./data:/app/data:ro,cached
    environment:
      - APISERVER_NUM_WORKERS=2
      - FROCKET_REDIS_HOST=redis
      - FROCKET_REDIS_PORT=${FROCKET_REDIS_PORT:-6379}
      - FROCKET_S3_AWS_ENDPOINT_URL=http://mock-s3:9000
      - FROCKET_S3_AWS_ACCESS_KEY_ID=testonly
      - FROCKET_S3_AWS_SECRET_ACCESS_KEY=testonly
      - FROCKET_LAMBDA_AWS_NO_SIGNATURE=true
      - FROCKET_LAMBDA_AWS_ENDPOINT_URL=http://mock-lambda:9001
      - FROCKET_LAMBDA_AWS_REGION=us-east-1
      - FROCKET_INVOKER_LAMBDA_LEGACY_ASYNC=false
      - FROCKET_INVOKER_RETRY_FAILED_INTERVAL=0.05
    #  - FROCKET_INVOKER=aws_lambda
    depends_on:
      - redis
    command: apiserver
