name: Tests
on: [ push ]
jobs:
  ci:
    runs-on: ubuntu-18.04
    timeout-minutes: 10

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2.3.4

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          architecture: 'x64'

      - name: Cache dependencies
        uses: actions/cache@v3.0.4
        id: cache-venv
        with:
          path: ./venv/
          key: ${{ runner.os }}-venv-cache-${{ hashFiles('./requirements.txt','./test-requirements.txt','./setup.py') }}

      - name: Build virtual environment and install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m venv venv
          source venv/bin/activate
          pip install -e .
          pip install -r test-requirements.txt
        if: steps.cache-venv.outputs.cache-hit != 'true'

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master

      - name: Cache Docker layers for all-in-one
        uses: actions/cache@v3.0.4
        with:
          path: /tmp/.buildx-cache-all-in-one
          key: ${{ runner.os }}-buildx-all-in-one-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-all-in-one-

      - name: Docker build all-in-one
        id: docker_build_all_in_one
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/all-in-one.Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          load: true
          tags: frocket/all-in-one:latest
          cache-from: type=local,src=/tmp/.buildx-cache-all-in-one
          cache-to: type=local,dest=/tmp/.buildx-cache-all-in-one,mode=max

      - name: Cache Docker layers for local-lambda
        uses: actions/cache@v3.0.4
        with:
          path: /tmp/.buildx-cache-local-lambda
          key: ${{ runner.os }}-buildx-local-lambda-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-local-lambda-

      - name: Docker build local-lambda
        id: docker_build_all_local_lambda
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/local-lambda.Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          load: true
          tags: frocket/local-lambda:latest
          cache-from: type=local,src=/tmp/.buildx-cache-local-lambda
          cache-to: type=local,dest=/tmp/.buildx-cache-local-lambda,mode=max

      - name: Launch docker-compose
        run: |
          docker-compose up -d
          sleep 2

      - name: Test with pytest
        run: |
          source venv/bin/activate
          export SKIP_SLOW_TESTS=true
          pytest --cov=frocket --cov-report=html
