name: Tests
on: [ push ]
jobs:
  ci:
    runs-on: ubuntu-18.04
    timeout-minutes: 5
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      mock-s3:
        image: frocket/minio-server-autostart:latest
        ports:
          - 9000:9000

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          architecture: 'x64'

      - name: Cache dependencies
        uses: actions/cache@v2
        id: cache-venv
        with:
          path: ./venv/
          key: ${{ runner.os }}-venvcache-${{ hashFiles('./requirements.txt','./requirements/test.txt','./setup.py') }}

      - name: Build virtual environment and install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m venv venv
          source venv/bin/activate
          pip install -e .
          pip install -r requirements/test.txt
        if: steps.cache-venv.outputs.cache-hit != 'true'

      - name: Test with pytest
        # Ignore test_invoker_api till queue_worker(s) run in this workflow
        run: |
          source venv/bin/activate
          export FROCKET_AWS_ENDPOINT_URL=http://127.0.0.1:9000
          export FROCKET_AWS_ACCESS_KEY_ID=testonly
          export FROCKET_AWS_SECRET_ACCESS_KEY=testonly
          FLASK_APP=frocket/apiserver.py python -m flask run &
          python -m frocket.worker.impl.queue_worker &
          python -m frocket.worker.impl.queue_worker &
          pytest --cov=frocket --cov-report=html
